import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div className="w-screen h-screen flex justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="game">
        <a className="text-5xl after:w-0 after:content-[''] after:block after:border-b-4 hover:after:w-full after:transition-all">
          Start
        </a>
      </Link>
    </div>
  );
}
